version: "3"

services:
  khanmedia:
    build: .
    ports:
      - 9090:9090
      - 9190:9190
      - 9290:9290
      - 9390:9390
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=$DB_NAME
      - SECRET_KEY=$SECRET_KEY
      - apikey=5acec106-ae16-ef11-af5d-00163e6496fc
    restart: always
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  proxy:
    image: envoyproxy/envoy:v1.18-latest
    ports:
      - 8080:8080
    volumes:
      - ./api/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    restart: always
  init-db:
    build:
      context: .
      dockerfile: Dockerfile.init-db
    depends_on:
      - postgres
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=$DB_NAME
    restart: "no"
volumes:
  postgres_data:
