// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: comment.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addComment = `-- name: AddComment :exec
INSERT INTO comment(post_id, profile_id, comment)
VALUES ($1, $2, $3)
`

type AddCommentParams struct {
	PostID    int64
	ProfileID int64
	Comment   string
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) error {
	_, err := q.db.ExecContext(ctx, addComment, arg.PostID, arg.ProfileID, arg.Comment)
	return err
}

const addReply = `-- name: AddReply :exec
INSERT INTO comment(parent_id, post_id, profile_id, comment)
VALUES ($1, $2, $3, $4)
`

type AddReplyParams struct {
	ParentID  sql.NullInt64
	PostID    int64
	ProfileID int64
	Comment   string
}

func (q *Queries) AddReply(ctx context.Context, arg AddReplyParams) error {
	_, err := q.db.ExecContext(ctx, addReply,
		arg.ParentID,
		arg.PostID,
		arg.ProfileID,
		arg.Comment,
	)
	return err
}

const getPostsComments = `-- name: GetPostsComments :many
SELECT account.username, profile.first_name, profile.profile_pic_address, comment.comment,
       (SELECT EXISTS
           (SELECT 1 FROM like_comment
            WHERE like_comment.comment_id = comment.id and like_comment.profile_id = $1)
       ) AS isLiked,
       (SELECT EXISTS
           (SELECT 1 FROM comment c
                WHERE c.parent_id = comment.id
           )
       ) AS has_replies,
       comment.time
FROM comment
    JOIN profile on comment.profile_id = profile.id
    JOIN account on profile.user_id = account.id
WHERE comment.parent_id IS NULL and comment.post_id = $2
`

type GetPostsCommentsParams struct {
	ProfileID int64
	PostID    int64
}

type GetPostsCommentsRow struct {
	Username          string
	FirstName         string
	ProfilePicAddress string
	Comment           string
	Isliked           bool
	HasReplies        bool
	Time              time.Time
}

func (q *Queries) GetPostsComments(ctx context.Context, arg GetPostsCommentsParams) ([]GetPostsCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsComments, arg.ProfileID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsCommentsRow
	for rows.Next() {
		var i GetPostsCommentsRow
		if err := rows.Scan(
			&i.Username,
			&i.FirstName,
			&i.ProfilePicAddress,
			&i.Comment,
			&i.Isliked,
			&i.HasReplies,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplies = `-- name: GetReplies :many
SELECT account.username,profile.first_name, profile.profile_pic_address, comment.comment,
       (lk.isLiked IS NOT NULL) AS isLiked,
       (SELECT EXISTS
                   (SELECT 1 FROM comment c
                    WHERE c.parent_id = comment.id
                   )
       ) AS has_replies,
       comment.time
FROM comment
         JOIN profile on comment.profile_id = profile.id
         JOIN account on profile.user_id = account.id
         LEFT JOIN (
            SELECT comment_id AS cmnt_id, 1 AS isLiked
            FROM like_comment
            WHERE like_comment.profile_id = $1
         ) AS lk on comment.id = lk.cmnt_id
WHERE comment.parent_id = $2
`

type GetRepliesParams struct {
	ProfileID int64
	ParentID  sql.NullInt64
}

type GetRepliesRow struct {
	Username          string
	FirstName         string
	ProfilePicAddress string
	Comment           string
	Isliked           interface{}
	HasReplies        bool
	Time              time.Time
}

func (q *Queries) GetReplies(ctx context.Context, arg GetRepliesParams) ([]GetRepliesRow, error) {
	rows, err := q.db.QueryContext(ctx, getReplies, arg.ProfileID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRepliesRow
	for rows.Next() {
		var i GetRepliesRow
		if err := rows.Scan(
			&i.Username,
			&i.FirstName,
			&i.ProfilePicAddress,
			&i.Comment,
			&i.Isliked,
			&i.HasReplies,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likeCommentOrReply = `-- name: LikeCommentOrReply :exec
INSERT INTO like_comment(profile_id, comment_id)
VALUES ($1, $2)
`

type LikeCommentOrReplyParams struct {
	ProfileID int64
	CommentID int64
}

func (q *Queries) LikeCommentOrReply(ctx context.Context, arg LikeCommentOrReplyParams) error {
	_, err := q.db.ExecContext(ctx, likeCommentOrReply, arg.ProfileID, arg.CommentID)
	return err
}
