// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: comment.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addComment = `-- name: AddComment :one
INSERT INTO comment(post_id, profile_id, comment)
VALUES ($1, $2, $3)
RETURNING id
`

type AddCommentParams struct {
	PostID    int64
	ProfileID int64
	Comment   string
}

func (q *Queries) AddComment(ctx context.Context, arg AddCommentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addComment, arg.PostID, arg.ProfileID, arg.Comment)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const addReply = `-- name: AddReply :one
WITH parent AS (
    SELECT post_id
    FROM comment
    WHERE id = $1
)
INSERT INTO comment(parent_id, post_id, profile_id, comment)
SELECT $1, parent.post_id, $2, $3
FROM parent
RETURNING id
`

type AddReplyParams struct {
	ParentID  sql.NullInt64
	ProfileID int64
	Comment   string
}

func (q *Queries) AddReply(ctx context.Context, arg AddReplyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, addReply, arg.ParentID, arg.ProfileID, arg.Comment)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE
FROM comment
WHERE profile_id = $1 AND id = $2
`

type DeleteCommentParams struct {
	ProfileID int64
	ID        int64
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, deleteComment, arg.ProfileID, arg.ID)
	return err
}

const dislikeCommentOrReply = `-- name: DislikeCommentOrReply :exec
DELETE
FROM profile_like_comment
WHERE profile_id = $1 and comment_id = $2
`

type DislikeCommentOrReplyParams struct {
	ProfileID int64
	CommentID int64
}

func (q *Queries) DislikeCommentOrReply(ctx context.Context, arg DislikeCommentOrReplyParams) error {
	_, err := q.db.ExecContext(ctx, dislikeCommentOrReply, arg.ProfileID, arg.CommentID)
	return err
}

const getComment = `-- name: GetComment :one
SELECT comment.id, account.username, profile.first_name, profile.profile_pic_address, comment.comment, comment.num_likes,
       (SELECT EXISTS
           (SELECT 1 FROM profile_like_comment
            WHERE profile_like_comment.comment_id = comment.id and profile_like_comment.profile_id = $1)
       ) AS isLiked,
       (SELECT EXISTS
           (SELECT 1 FROM comment c
                WHERE c.parent_id = comment.id
           )
       ) AS has_replies,
       comment.profile_id = $1 AS owned,
       comment.time
FROM comment
    JOIN profile on comment.profile_id = profile.id
    JOIN account on profile.user_id = account.id
WHERE comment.id = $2
`

type GetCommentParams struct {
	ProfileID int64
	ID        int64
}

type GetCommentRow struct {
	ID                int64
	Username          string
	FirstName         string
	ProfilePicAddress string
	Comment           string
	NumLikes          int32
	Isliked           bool
	HasReplies        bool
	Owned             bool
	Time              time.Time
}

func (q *Queries) GetComment(ctx context.Context, arg GetCommentParams) (GetCommentRow, error) {
	row := q.db.QueryRowContext(ctx, getComment, arg.ProfileID, arg.ID)
	var i GetCommentRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.ProfilePicAddress,
		&i.Comment,
		&i.NumLikes,
		&i.Isliked,
		&i.HasReplies,
		&i.Owned,
		&i.Time,
	)
	return i, err
}

const getPostsComments = `-- name: GetPostsComments :many
SELECT comment.id, account.username, profile.first_name, profile.profile_pic_address, comment.comment, comment.num_likes,
       (SELECT EXISTS
           (SELECT 1 FROM profile_like_comment
            WHERE profile_like_comment.comment_id = comment.id and profile_like_comment.profile_id = $1)
       ) AS isLiked,
       (SELECT EXISTS
           (SELECT 1 FROM comment c
                WHERE c.parent_id = comment.id
           )
       ) AS has_replies,
       comment.profile_id = $1 AS owned,
       comment.time
FROM comment
    JOIN profile on comment.profile_id = profile.id
    JOIN account on profile.user_id = account.id
WHERE comment.parent_id IS NULL and comment.post_id = $2 and num_report < 1000
`

type GetPostsCommentsParams struct {
	ProfileID int64
	PostID    int64
}

type GetPostsCommentsRow struct {
	ID                int64
	Username          string
	FirstName         string
	ProfilePicAddress string
	Comment           string
	NumLikes          int32
	Isliked           bool
	HasReplies        bool
	Owned             bool
	Time              time.Time
}

func (q *Queries) GetPostsComments(ctx context.Context, arg GetPostsCommentsParams) ([]GetPostsCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsComments, arg.ProfileID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsCommentsRow
	for rows.Next() {
		var i GetPostsCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.ProfilePicAddress,
			&i.Comment,
			&i.NumLikes,
			&i.Isliked,
			&i.HasReplies,
			&i.Owned,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplies = `-- name: GetReplies :many
SELECT comment.id, account.username,profile.first_name, profile.profile_pic_address, comment.comment, comment.num_likes,
       (lk.isLiked IS NOT NULL) AS isLiked,
       (SELECT EXISTS
                   (SELECT 1 FROM comment c
                    WHERE c.parent_id = comment.id
                   )
       ) AS has_replies,
       comment.profile_id = $1 AS owned,
       comment.time
FROM comment
         JOIN profile on comment.profile_id = profile.id
         JOIN account on profile.user_id = account.id
         LEFT JOIN (
            SELECT comment_id AS cmnt_id, 1 AS isLiked
            FROM profile_like_comment
            WHERE profile_like_comment.profile_id = $1
         ) AS lk on comment.id = lk.cmnt_id
WHERE comment.parent_id = $2 and num_report < 1000
`

type GetRepliesParams struct {
	ProfileID int64
	ParentID  sql.NullInt64
}

type GetRepliesRow struct {
	ID                int64
	Username          string
	FirstName         string
	ProfilePicAddress string
	Comment           string
	NumLikes          int32
	Isliked           interface{}
	HasReplies        bool
	Owned             bool
	Time              time.Time
}

func (q *Queries) GetReplies(ctx context.Context, arg GetRepliesParams) ([]GetRepliesRow, error) {
	rows, err := q.db.QueryContext(ctx, getReplies, arg.ProfileID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRepliesRow
	for rows.Next() {
		var i GetRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.ProfilePicAddress,
			&i.Comment,
			&i.NumLikes,
			&i.Isliked,
			&i.HasReplies,
			&i.Owned,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likeCommentOrReply = `-- name: LikeCommentOrReply :exec
INSERT INTO profile_like_comment(profile_id, comment_id)
VALUES ($1, $2)
`

type LikeCommentOrReplyParams struct {
	ProfileID int64
	CommentID int64
}

func (q *Queries) LikeCommentOrReply(ctx context.Context, arg LikeCommentOrReplyParams) error {
	_, err := q.db.ExecContext(ctx, likeCommentOrReply, arg.ProfileID, arg.CommentID)
	return err
}

const reportComment = `-- name: ReportComment :exec
INSERT INTO report_comment (profile_id, comment_id) values ($1, $2)
`

type ReportCommentParams struct {
	ProfileID int64
	CommentID int64
}

func (q *Queries) ReportComment(ctx context.Context, arg ReportCommentParams) error {
	_, err := q.db.ExecContext(ctx, reportComment, arg.ProfileID, arg.CommentID)
	return err
}
