// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: follow.sql

package db

import (
	"context"
)

const follow = `-- name: Follow :exec
INSERT INTO follow (follower, following) VALUES ($1, $2)
`

type FollowParams struct {
	Follower  int64
	Following int64
}

func (q *Queries) Follow(ctx context.Context, arg FollowParams) error {
	_, err := q.db.ExecContext(ctx, follow, arg.Follower, arg.Following)
	return err
}

const followStatus = `-- name: FollowStatus :one
SELECT EXISTS (
    SELECT 1
    FROM follow
    WHERE follower = $1 AND following = $2
)
`

type FollowStatusParams struct {
	Follower  int64
	Following int64
}

func (q *Queries) FollowStatus(ctx context.Context, arg FollowStatusParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, followStatus, arg.Follower, arg.Following)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const followerList = `-- name: FollowerList :many
SELECT profile.id, account.username,  (profile.first_name || ' ' || profile.last_name) AS name, profile.profile_pic_address,
       (SELECT EXISTS(SELECT 1 FROM follow f WHERE f.follower = $1 and f.following = profile.id)) AS is_followed
FROM follow JOIN profile on follow.follower = profile.id
    JOIN account on profile.user_id = account.id
WHERE follow.following = $2
`

type FollowerListParams struct {
	Myprofile int64
	Profileid int64
}

type FollowerListRow struct {
	ID                int64
	Username          string
	Name              interface{}
	ProfilePicAddress string
	IsFollowed        bool
}

func (q *Queries) FollowerList(ctx context.Context, arg FollowerListParams) ([]FollowerListRow, error) {
	rows, err := q.db.QueryContext(ctx, followerList, arg.Myprofile, arg.Profileid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowerListRow
	for rows.Next() {
		var i FollowerListRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.ProfilePicAddress,
			&i.IsFollowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const followingList = `-- name: FollowingList :many
SELECT profile.id, account.username,  (profile.first_name || ' ' || profile.last_name) AS name, profile.profile_pic_address,
       (SELECT EXISTS(SELECT 1 FROM follow f WHERE f.follower = $1 and f.following = profile.id)) AS is_followed
FROM follow JOIN profile on follow.following = profile.id
    JOIN account on profile.user_id = account.id
WHERE follow.follower = $2
`

type FollowingListParams struct {
	Myprofile int64
	Profileid int64
}

type FollowingListRow struct {
	ID                int64
	Username          string
	Name              interface{}
	ProfilePicAddress string
	IsFollowed        bool
}

func (q *Queries) FollowingList(ctx context.Context, arg FollowingListParams) ([]FollowingListRow, error) {
	rows, err := q.db.QueryContext(ctx, followingList, arg.Myprofile, arg.Profileid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowingListRow
	for rows.Next() {
		var i FollowingListRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Name,
			&i.ProfilePicAddress,
			&i.IsFollowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowerCnt = `-- name: GetFollowerCnt :one
SELECT count(*)
FROM follow
WHERE following = $1
`

func (q *Queries) GetFollowerCnt(ctx context.Context, following int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFollowerCnt, following)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFollowingCnt = `-- name: GetFollowingCnt :one
SELECT count(*)
FROM follow
WHERE follower = $1
`

func (q *Queries) GetFollowingCnt(ctx context.Context, follower int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFollowingCnt, follower)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM follow
WHERE follower = $1 and following = $2
`

type UnfollowParams struct {
	Follower  int64
	Following int64
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.Follower, arg.Following)
	return err
}
