// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post.sql

package db

import (
	"context"
)

const getPost = `-- name: GetPost :one
SELECT id, title, description, num_images, profile_id
FROM post
WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.NumImages,
		&i.ProfileID,
	)
	return i, err
}

const insertPost = `-- name: InsertPost :one
INSERT INTO post (title, description, num_images, profile_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertPostParams struct {
	Title       string
	Description string
	NumImages   int16
	ProfileID   int64
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPost,
		arg.Title,
		arg.Description,
		arg.NumImages,
		arg.ProfileID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
