// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: post.sql

package db

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const addImage = `-- name: AddImage :exec
WITH post_image_cnt AS (
    SELECT COUNT(*) as cnt
    FROM post_image
    WHERE post_id = $1
)
INSERT INTO post_image (post_id, image_url, is_primary)
SELECT $1, $2, (cnt < 1)::boolean
FROM post_image_cnt
`

type AddImageParams struct {
	PostID   int64
	ImageUrl string
}

func (q *Queries) AddImage(ctx context.Context, arg AddImageParams) error {
	_, err := q.db.ExecContext(ctx, addImage, arg.PostID, arg.ImageUrl)
	return err
}

const getPost = `-- name: GetPost :one
SELECT post.id, post.title, post.description, category.name as category, account.username, profile.profile_pic_address, post.num_images, post.num_likes
FROM post
         JOIN profile on profile.id = post.profile_id
         JOIN account on account.id = profile.user_id
         JOIN category on post.category_id = category.id
WHERE post.id = $1
`

type GetPostRow struct {
	ID                int64
	Title             string
	Description       string
	Category          string
	Username          string
	ProfilePicAddress string
	NumImages         int16
	NumLikes          int32
}

func (q *Queries) GetPost(ctx context.Context, id int64) (GetPostRow, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Username,
		&i.ProfilePicAddress,
		&i.NumImages,
		&i.NumLikes,
	)
	return i, err
}

const getPostImages = `-- name: GetPostImages :many
SELECT post_image.image_url
FROM post_image
WHERE post_id = $1
ORDER BY id
`

func (q *Queries) GetPostImages(ctx context.Context, postID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getPostImages, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_url string
		if err := rows.Scan(&image_url); err != nil {
			return nil, err
		}
		items = append(items, image_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostOwnerProfile = `-- name: GetPostOwnerProfile :one
SELECT post.profile_id AS profile_id
FROM post
WHERE id = $1
`

func (q *Queries) GetPostOwnerProfile(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPostOwnerProfile, id)
	var profile_id int64
	err := row.Scan(&profile_id)
	return profile_id, err
}

const getPostsPreview = `-- name: GetPostsPreview :many
SELECT post.id, post.title, post.description, post_image.image_url
FROM post
    LEFT JOIN post_image on post.id = post_image.post_id
WHERE post.profile_id = $1 and post_image.is_primary = true
ORDER BY post.id
LIMIT 20
`

type GetPostsPreviewRow struct {
	ID          int64
	Title       string
	Description string
	ImageUrl    sql.NullString
}

func (q *Queries) GetPostsPreview(ctx context.Context, profileID int64) ([]GetPostsPreviewRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsPreview, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsPreviewRow
	for rows.Next() {
		var i GetPostsPreviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostsWithCategory = `-- name: GetPostsWithCategory :many
SELECT post.id, title, description, post_image.image_url as post_image, username, profile_pic_address
FROM post
	INNER JOIN profile ON post.profile_id = profile.id
	LEFT JOIN post_image ON post.id = post_image.post_id
	INNER JOIN account ON profile.user_id = account.id
WHERE category_id = ANY($1::int[]) and is_primary = true
`

type GetPostsWithCategoryRow struct {
	ID                int64
	Title             string
	Description       string
	PostImage         sql.NullString
	Username          string
	ProfilePicAddress string
}

func (q *Queries) GetPostsWithCategory(ctx context.Context, dollar_1 []int32) ([]GetPostsWithCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsWithCategory, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsWithCategoryRow
	for rows.Next() {
		var i GetPostsWithCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.PostImage,
			&i.Username,
			&i.ProfilePicAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPost = `-- name: InsertPost :one
INSERT INTO post (title, description, category_id, num_images, profile_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertPostParams struct {
	Title       string
	Description string
	CategoryID  int16
	NumImages   int16
	ProfileID   int64
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertPost,
		arg.Title,
		arg.Description,
		arg.CategoryID,
		arg.NumImages,
		arg.ProfileID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const postImageCount = `-- name: PostImageCount :one
SELECT count(*)
FROM post_image
WHERE post_id = $1
`

func (q *Queries) PostImageCount(ctx context.Context, postID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, postImageCount, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchIngredient = `-- name: SearchIngredient :many
WITH selected_post_id AS (
      SELECT post_has_ingredient.post_id AS p_id
      FROM post_has_ingredient
               JOIN ingredient on post_has_ingredient.ingredient_id = ingredient.id
      WHERE ingredient.name = ANY ($2::TEXT[])
      GROUP BY post_has_ingredient.post_id
      HAVING COUNT(DISTINCT ingredient.id) = $3
      INTERSECT
      SELECT post_has_ingredient.post_id AS p_id
      FROM post_has_ingredient
               JOIN ingredient on post_has_ingredient.ingredient_id = ingredient.id
      WHERE NOT EXISTS (SELECT 1
                        FROM post_has_ingredient phi
                            JOIN ingredient ing on phi.ingredient_id = ing.id
                        WHERE phi.post_id = post_has_ingredient.post_id
                            and ing.name = ANY ($4::TEXT[]))
)
SELECT post.id, post.title, post.description,
       post_image.image_url, account.username, profile.profile_pic_address
FROM selected_post_id
    JOIN post on post.id = selected_post_id.p_id
    JOIN profile on post.profile_id = profile.id
    JOIN account on profile.user_id = account.id
    LEFT JOIN post_image on post.id = post_image.post_id
WHERE post_image.is_primary = true
ORDER BY post.num_likes DESC
OFFSET $1
LIMIT 20
`

type SearchIngredientParams struct {
	Page       int32
	Include    []string
	Includecnt int32
	Exclude    []string
}

type SearchIngredientRow struct {
	ID                int64
	Title             string
	Description       string
	ImageUrl          sql.NullString
	Username          string
	ProfilePicAddress string
}

func (q *Queries) SearchIngredient(ctx context.Context, arg SearchIngredientParams) ([]SearchIngredientRow, error) {
	rows, err := q.db.QueryContext(ctx, searchIngredient,
		arg.Page,
		pq.Array(arg.Include),
		arg.Includecnt,
		pq.Array(arg.Exclude),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchIngredientRow
	for rows.Next() {
		var i SearchIngredientRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.Username,
			&i.ProfilePicAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchName = `-- name: SearchName :many
SELECT post.id, post.title, post.description, post_image.image_url,
       profile.profile_pic_address, account.username
FROM post
    JOIN profile on post.profile_id = profile.id
    JOIN account on profile.user_id = account.id
    LEFT JOIN post_image on post.id = post_image.post_id
WHERE post_image.is_primary = true and similarity(post.title, $1) > 0.5
ORDER BY (similarity(post.title, $1), post.num_likes) DESC
OFFSET $2
LIMIT 20
`

type SearchNameParams struct {
	Name string
	Page int32
}

type SearchNameRow struct {
	ID                int64
	Title             string
	Description       string
	ImageUrl          sql.NullString
	ProfilePicAddress string
	Username          string
}

func (q *Queries) SearchName(ctx context.Context, arg SearchNameParams) ([]SearchNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchName, arg.Name, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNameRow
	for rows.Next() {
		var i SearchNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ImageUrl,
			&i.ProfilePicAddress,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
