// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: profile_like_post.sql

package db

import (
	"context"
)

const dislikePost = `-- name: DislikePost :exec
DELETE
FROM profile_like_post
WHERE post_id = $1 AND profile_id = $2
`

type DislikePostParams struct {
	PostID    int64
	ProfileID int64
}

func (q *Queries) DislikePost(ctx context.Context, arg DislikePostParams) error {
	_, err := q.db.ExecContext(ctx, dislikePost, arg.PostID, arg.ProfileID)
	return err
}

const likePost = `-- name: LikePost :exec
INSERT INTO profile_like_post (profile_id, post_id)
VALUES ($1, $2)
`

type LikePostParams struct {
	ProfileID int64
	PostID    int64
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.ExecContext(ctx, likePost, arg.ProfileID, arg.PostID)
	return err
}

const profileLikePost = `-- name: ProfileLikePost :one
SELECT COUNT(*)
FROM profile_like_post
WHERE profile_id = $1 AND post_id = $2
`

type ProfileLikePostParams struct {
	ProfileID int64
	PostID    int64
}

func (q *Queries) ProfileLikePost(ctx context.Context, arg ProfileLikePostParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, profileLikePost, arg.ProfileID, arg.PostID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
