// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: profile_pin_post.sql

package db

import (
	"context"
	"database/sql"
)

const addPin = `-- name: AddPin :exec
INSERT INTO profile_pin_post(profile_id, post_id)
VALUES ($1, $2)
`

type AddPinParams struct {
	ProfileID int64
	PostID    int64
}

func (q *Queries) AddPin(ctx context.Context, arg AddPinParams) error {
	_, err := q.db.ExecContext(ctx, addPin, arg.ProfileID, arg.PostID)
	return err
}

const getPins = `-- name: GetPins :many
SELECT post.title, post_image.image_url
FROM profile_pin_post
    JOIN post ON profile_pin_post.post_id = post.id
    LEFT JOIN post_image ON profile_pin_post.post_id = post_image.post_id
WHERE profile_pin_post.profile_id = $1 AND post_image.is_primary = TRUE
`

type GetPinsRow struct {
	Title    string
	ImageUrl sql.NullString
}

func (q *Queries) GetPins(ctx context.Context, profileID int64) ([]GetPinsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPins, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPinsRow
	for rows.Next() {
		var i GetPinsRow
		if err := rows.Scan(&i.Title, &i.ImageUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPinsCount = `-- name: GetPinsCount :one
SELECT count(*)
FROM profile_pin_post
WHERE profile_id = $1
`

func (q *Queries) GetPinsCount(ctx context.Context, profileID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getPinsCount, profileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const removePin = `-- name: RemovePin :exec
DELETE
FROM profile_pin_post
WHERE profile_id = $1 AND post_id = $2
`

type RemovePinParams struct {
	ProfileID int64
	PostID    int64
}

func (q *Queries) RemovePin(ctx context.Context, arg RemovePinParams) error {
	_, err := q.db.ExecContext(ctx, removePin, arg.ProfileID, arg.PostID)
	return err
}
