// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: profile.sql

package db

import (
	"context"
	"database/sql"
)

const changeProfilePic = `-- name: ChangeProfilePic :exec
UPDATE profile
SET profile_pic_address = $1
WHERE user_id = $2
`

type ChangeProfilePicParams struct {
	ProfilePicAddress sql.NullString
	UserID            int64
}

func (q *Queries) ChangeProfilePic(ctx context.Context, arg ChangeProfilePicParams) error {
	_, err := q.db.ExecContext(ctx, changeProfilePic, arg.ProfilePicAddress, arg.UserID)
	return err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profile (user_id)
VALUES ($1)
`

func (q *Queries) CreateProfile(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, createProfile, userID)
	return err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT profile.id, account.username, profile.first_name || profile.last_name AS name,
       profile.bio, profile.gender, city.name, profile.profile_pic_address
FROM profile JOIN account on account.id = profile.user_id
             JOIN city on city.id = profile.city_id
WHERE account.id = $1
`

type GetProfileByUserIDRow struct {
	ID                int64
	Username          string
	Name              string
	Bio               string
	Gender            Gender
	Name_2            string
	ProfilePicAddress sql.NullString
}

func (q *Queries) GetProfileByUserID(ctx context.Context, id int64) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUserID, id)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Bio,
		&i.Gender,
		&i.Name_2,
		&i.ProfilePicAddress,
	)
	return i, err
}

const getProfileByUsername = `-- name: GetProfileByUsername :one
SELECT profile.id, account.username, profile.first_name || profile.last_name AS name,
       profile.bio, profile.gender, city.name, profile.profile_pic_address
FROM profile JOIN account on account.id = profile.user_id
    JOIN city on city.id = profile.city_id
WHERE account.username = $1
`

type GetProfileByUsernameRow struct {
	ID                int64
	Username          string
	Name              string
	Bio               string
	Gender            Gender
	Name_2            string
	ProfilePicAddress sql.NullString
}

func (q *Queries) GetProfileByUsername(ctx context.Context, username string) (GetProfileByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getProfileByUsername, username)
	var i GetProfileByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.Bio,
		&i.Gender,
		&i.Name_2,
		&i.ProfilePicAddress,
	)
	return i, err
}

const getUserInfo = `-- name: GetUserInfo :one
SELECT account.username, profile.first_name, profile.last_name,
       profile.gender, profile.birth_day, profile.bio,
       city.name AS city_name, profile.city_id, account.email
FROM profile JOIN account on account.id = profile.user_id
    JOIN city on city.id = profile.city_id
WHERE user_id = $1
`

type GetUserInfoRow struct {
	Username  string
	FirstName sql.NullString
	LastName  sql.NullString
	Gender    Gender
	BirthDay  sql.NullTime
	Bio       string
	CityName  string
	CityID    sql.NullInt16
	Email     string
}

func (q *Queries) GetUserInfo(ctx context.Context, userID int64) (GetUserInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getUserInfo, userID)
	var i GetUserInfoRow
	err := row.Scan(
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
		&i.BirthDay,
		&i.Bio,
		&i.CityName,
		&i.CityID,
		&i.Email,
	)
	return i, err
}

const updateProfileInfo = `-- name: UpdateProfileInfo :exec
UPDATE profile
SET	    first_name = $1,
        last_name  = $2,
        gender	   = $3,
        birth_day  = $4,
        bio        = $5,
        city_id    = $6
WHERE user_id = $7
`

type UpdateProfileInfoParams struct {
	FirstName sql.NullString
	LastName  sql.NullString
	Gender    Gender
	BirthDay  sql.NullTime
	Bio       string
	CityID    sql.NullInt16
	UserID    int64
}

func (q *Queries) UpdateProfileInfo(ctx context.Context, arg UpdateProfileInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateProfileInfo,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.BirthDay,
		arg.Bio,
		arg.CityID,
		arg.UserID,
	)
	return err
}
