// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: signin.sql

package db

import (
	"context"
	"time"
)

const deleteSignin = `-- name: DeleteSignin :exec
DELETE
FROM signin
WHERE id = $1
`

func (q *Queries) DeleteSignin(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteSignin, id)
	return err
}

const getSigninCode = `-- name: GetSigninCode :one
SELECT verification_code
FROM signin
WHERE id = $1
`

func (q *Queries) GetSigninCode(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRowContext(ctx, getSigninCode, id)
	var verification_code string
	err := row.Scan(&verification_code)
	return verification_code, err
}

const insertSignin = `-- name: InsertSignin :one
INSERT INTO signin (email, username, password, verification_code, expire)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertSigninParams struct {
	Email            string
	Username         string
	Password         string
	VerificationCode string
	Expire           time.Time
}

func (q *Queries) InsertSignin(ctx context.Context, arg InsertSigninParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertSignin,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.VerificationCode,
		arg.Expire,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
