// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE
FROM account
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const existsUserEmail = `-- name: ExistsUserEmail :one
SELECT count(*)
FROM account
WHERE email = $1
`

func (q *Queries) ExistsUserEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsUserEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsUserUsername = `-- name: ExistsUserUsername :one
SELECT count(*)
FROM account
WHERE username = $1
`

func (q *Queries) ExistsUserUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsUserUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, creation_date, password
FROM account
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreationDate,
		&i.Password,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, creation_date, password
FROM account
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreationDate,
		&i.Password,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, creation_date, password
FROM account
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreationDate,
		&i.Password,
	)
	return i, err
}

const getUserIDbyProfileID = `-- name: GetUserIDbyProfileID :one
SELECT account.id
FROM account
    JOIN profile on account.id = profile.user_id
WHERE profile.id = $1
`

func (q *Queries) GetUserIDbyProfileID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserIDbyProfileID, id)
	err := row.Scan(&id)
	return id, err
}

const getUserPasswordByEmail = `-- name: GetUserPasswordByEmail :one
SELECT password
FROM account
WHERE email = $1
`

func (q *Queries) GetUserPasswordByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordByEmail, email)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getUserPasswordByUsername = `-- name: GetUserPasswordByUsername :one
select password
FROM account
WHERE username = $1
`

func (q *Queries) GetUserPasswordByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordByUsername, username)
	var password string
	err := row.Scan(&password)
	return password, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO account (email, username, password)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertUserParams struct {
	Email    string
	Username string
	Password string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertUser, arg.Email, arg.Username, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const resetPassword = `-- name: ResetPassword :exec
UPDATE account
SET password = $2
WHERE id = $1
`

type ResetPasswordParams struct {
	ID       int64
	Password string
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) error {
	_, err := q.db.ExecContext(ctx, resetPassword, arg.ID, arg.Password)
	return err
}

const searchUsername = `-- name: SearchUsername :many
WITH username_similarity AS (
    SELECT profile.id, username, first_name, profile_pic_address, similarity(username, $1) AS similarity
    FROM account INNER JOIN profile on account.id = profile.user_id
)
SELECT id, username, first_name, profile_pic_address
FROM username_similarity
WHERE similarity > 0.3 
ORDER BY similarity DESC
LIMIT 50
`

type SearchUsernameRow struct {
	ID                int64
	Username          string
	FirstName         string
	ProfilePicAddress string
}

func (q *Queries) SearchUsername(ctx context.Context, username string) ([]SearchUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsername, username)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsernameRow
	for rows.Next() {
		var i SearchUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FirstName,
			&i.ProfilePicAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
