// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const existsUserEmail = `-- name: ExistsUserEmail :one
SELECT count(*)
FROM account
WHERE email = $1
`

func (q *Queries) ExistsUserEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsUserEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const existsUserUsername = `-- name: ExistsUserUsername :one
SELECT count(*)
FROM account
WHERE username = $1
`

func (q *Queries) ExistsUserUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, existsUserUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserPasswordByEmail = `-- name: GetUserPasswordByEmail :one
SELECT password
FROM account
WHERE email = $1
`

func (q *Queries) GetUserPasswordByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordByEmail, email)
	var password string
	err := row.Scan(&password)
	return password, err
}

const getUserPasswordByUsername = `-- name: GetUserPasswordByUsername :one
select password
FROM account
WHERE username = $1
`

func (q *Queries) GetUserPasswordByUsername(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserPasswordByUsername, username)
	var password string
	err := row.Scan(&password)
	return password, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO account (email, username, password)
VALUES ($1, $2, $3)
`

type InsertUserParams struct {
	Email    string
	Username string
	Password string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.Email, arg.Username, arg.Password)
	return err
}

const updateUserInfo = `-- name: UpdateUserInfo :exec
UPDATE account
SET	first_name = $1,
	last_name  = $2,
	gender	   = $3,
	birth_day  = $4
WHERE username = $5
`

type UpdateUserInfoParams struct {
	FirstName sql.NullString
	LastName  sql.NullString
	Gender    NullGender
	BirthDay  sql.NullTime
	Username  string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) error {
	_, err := q.db.ExecContext(ctx, updateUserInfo,
		arg.FirstName,
		arg.LastName,
		arg.Gender,
		arg.BirthDay,
		arg.Username,
	)
	return err
}
