// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package SearchAPIService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchAPIClient is the client API for SearchAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchAPIClient interface {
	GetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	SearchFoodByName(ctx context.Context, in *SearchFoodByNameRequest, opts ...grpc.CallOption) (*SearchFoodByNameResponse, error)
	SearchFoodByIngredient(ctx context.Context, in *SearchFoodByIngredientRequest, opts ...grpc.CallOption) (*SearchFoodByIngredientResponse, error)
	SearchCategories(ctx context.Context, in *SearchCategoriesRequest, opts ...grpc.CallOption) (*SearchCategoriesResponse, error)
}

type searchAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchAPIClient(cc grpc.ClientConnInterface) SearchAPIClient {
	return &searchAPIClient{cc}
}

func (c *searchAPIClient) GetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.SearchAPI/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchAPIClient) SearchFoodByName(ctx context.Context, in *SearchFoodByNameRequest, opts ...grpc.CallOption) (*SearchFoodByNameResponse, error) {
	out := new(SearchFoodByNameResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.SearchAPI/SearchFoodByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchAPIClient) SearchFoodByIngredient(ctx context.Context, in *SearchFoodByIngredientRequest, opts ...grpc.CallOption) (*SearchFoodByIngredientResponse, error) {
	out := new(SearchFoodByIngredientResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.SearchAPI/SearchFoodByIngredient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchAPIClient) SearchCategories(ctx context.Context, in *SearchCategoriesRequest, opts ...grpc.CallOption) (*SearchCategoriesResponse, error) {
	out := new(SearchCategoriesResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.SearchAPI/SearchCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchAPIServer is the server API for SearchAPI service.
// All implementations must embed UnimplementedSearchAPIServer
// for forward compatibility
type SearchAPIServer interface {
	GetCategories(context.Context, *emptypb.Empty) (*GetCategoriesResponse, error)
	SearchFoodByName(context.Context, *SearchFoodByNameRequest) (*SearchFoodByNameResponse, error)
	SearchFoodByIngredient(context.Context, *SearchFoodByIngredientRequest) (*SearchFoodByIngredientResponse, error)
	SearchCategories(context.Context, *SearchCategoriesRequest) (*SearchCategoriesResponse, error)
	mustEmbedUnimplementedSearchAPIServer()
}

// UnimplementedSearchAPIServer must be embedded to have forward compatible implementations.
type UnimplementedSearchAPIServer struct {
}

func (UnimplementedSearchAPIServer) GetCategories(context.Context, *emptypb.Empty) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedSearchAPIServer) SearchFoodByName(context.Context, *SearchFoodByNameRequest) (*SearchFoodByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFoodByName not implemented")
}
func (UnimplementedSearchAPIServer) SearchFoodByIngredient(context.Context, *SearchFoodByIngredientRequest) (*SearchFoodByIngredientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchFoodByIngredient not implemented")
}
func (UnimplementedSearchAPIServer) SearchCategories(context.Context, *SearchCategoriesRequest) (*SearchCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCategories not implemented")
}
func (UnimplementedSearchAPIServer) mustEmbedUnimplementedSearchAPIServer() {}

// UnsafeSearchAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchAPIServer will
// result in compilation errors.
type UnsafeSearchAPIServer interface {
	mustEmbedUnimplementedSearchAPIServer()
}

func RegisterSearchAPIServer(s grpc.ServiceRegistrar, srv SearchAPIServer) {
	s.RegisterService(&SearchAPI_ServiceDesc, srv)
}

func _SearchAPI_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchAPIServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.SearchAPI/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchAPIServer).GetCategories(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchAPI_SearchFoodByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFoodByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchAPIServer).SearchFoodByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.SearchAPI/SearchFoodByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchAPIServer).SearchFoodByName(ctx, req.(*SearchFoodByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchAPI_SearchFoodByIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFoodByIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchAPIServer).SearchFoodByIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.SearchAPI/SearchFoodByIngredient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchAPIServer).SearchFoodByIngredient(ctx, req.(*SearchFoodByIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchAPI_SearchCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchAPIServer).SearchCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.SearchAPI/SearchCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchAPIServer).SearchCategories(ctx, req.(*SearchCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchAPI_ServiceDesc is the grpc.ServiceDesc for SearchAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KhanAPI.SearchAPI",
	HandlerType: (*SearchAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategories",
			Handler:    _SearchAPI_GetCategories_Handler,
		},
		{
			MethodName: "SearchFoodByName",
			Handler:    _SearchAPI_SearchFoodByName_Handler,
		},
		{
			MethodName: "SearchFoodByIngredient",
			Handler:    _SearchAPI_SearchFoodByIngredient_Handler,
		},
		{
			MethodName: "SearchCategories",
			Handler:    _SearchAPI_SearchCategories_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
