// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package PostAPIService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostAPIClient is the client API for PostAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostAPIClient interface {
	GetProfilePosts(ctx context.Context, in *GetProfilePostsRequests, opts ...grpc.CallOption) (*GetProfilePostsResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
}

type postAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPostAPIClient(cc grpc.ClientConnInterface) PostAPIClient {
	return &postAPIClient{cc}
}

func (c *postAPIClient) GetProfilePosts(ctx context.Context, in *GetProfilePostsRequests, opts ...grpc.CallOption) (*GetProfilePostsResponse, error) {
	out := new(GetProfilePostsResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/GetProfilePosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostAPIServer is the server API for PostAPI service.
// All implementations must embed UnimplementedPostAPIServer
// for forward compatibility
type PostAPIServer interface {
	GetProfilePosts(context.Context, *GetProfilePostsRequests) (*GetProfilePostsResponse, error)
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
	mustEmbedUnimplementedPostAPIServer()
}

// UnimplementedPostAPIServer must be embedded to have forward compatible implementations.
type UnimplementedPostAPIServer struct {
}

func (UnimplementedPostAPIServer) GetProfilePosts(context.Context, *GetProfilePostsRequests) (*GetProfilePostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfilePosts not implemented")
}
func (UnimplementedPostAPIServer) GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (UnimplementedPostAPIServer) mustEmbedUnimplementedPostAPIServer() {}

// UnsafePostAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostAPIServer will
// result in compilation errors.
type UnsafePostAPIServer interface {
	mustEmbedUnimplementedPostAPIServer()
}

func RegisterPostAPIServer(s grpc.ServiceRegistrar, srv PostAPIServer) {
	s.RegisterService(&PostAPI_ServiceDesc, srv)
}

func _PostAPI_GetProfilePosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfilePostsRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).GetProfilePosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/GetProfilePosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).GetProfilePosts(ctx, req.(*GetProfilePostsRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostAPI_ServiceDesc is the grpc.ServiceDesc for PostAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KhanAPI.PostAPI",
	HandlerType: (*PostAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfilePosts",
			Handler:    _PostAPI_GetProfilePosts_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostAPI_GetPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
