// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: api/proto/post.proto

package PostAPIService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostAPIClient is the client API for PostAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostAPIClient interface {
	GetProfilePosts(ctx context.Context, in *GetProfilePostsRequests, opts ...grpc.CallOption) (*GetProfilePostsResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
	SetPost(ctx context.Context, in *SetPostRequest, opts ...grpc.CallOption) (*SetPostResponse, error)
	GetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	SuggestIngredient(ctx context.Context, in *SuggestIngredientRequest, opts ...grpc.CallOption) (*SuggestIngredientResponse, error)
	AddImageForPost(ctx context.Context, in *AddImageForPostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Dislike(ctx context.Context, in *DislikeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*Comment, error)
	AddReply(ctx context.Context, in *AddReplyRequest, opts ...grpc.CallOption) (*Comment, error)
	GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error)
	GetReplies(ctx context.Context, in *GetRepliesRequest, opts ...grpc.CallOption) (*GetRepliesResponse, error)
	LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DislikeComment(ctx context.Context, in *DislikeCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReportComment(ctx context.Context, in *RepostCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PinPost(ctx context.Context, in *PinPostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnpinPost(ctx context.Context, in *UnpinPostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPins(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPinsResponse, error)
}

type postAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPostAPIClient(cc grpc.ClientConnInterface) PostAPIClient {
	return &postAPIClient{cc}
}

func (c *postAPIClient) GetProfilePosts(ctx context.Context, in *GetProfilePostsRequests, opts ...grpc.CallOption) (*GetProfilePostsResponse, error) {
	out := new(GetProfilePostsResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/GetProfilePosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) SetPost(ctx context.Context, in *SetPostRequest, opts ...grpc.CallOption) (*SetPostResponse, error) {
	out := new(SetPostResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/SetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) GetCategories(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/GetCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) SuggestIngredient(ctx context.Context, in *SuggestIngredientRequest, opts ...grpc.CallOption) (*SuggestIngredientResponse, error) {
	out := new(SuggestIngredientResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/SuggestIngredient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) AddImageForPost(ctx context.Context, in *AddImageForPostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/AddImageForPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) Like(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/Like", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) Dislike(ctx context.Context, in *DislikeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/Dislike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) AddComment(ctx context.Context, in *AddCommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/AddComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) AddReply(ctx context.Context, in *AddReplyRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/AddReply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) GetComments(ctx context.Context, in *GetCommentsRequest, opts ...grpc.CallOption) (*GetCommentsResponse, error) {
	out := new(GetCommentsResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/GetComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) GetReplies(ctx context.Context, in *GetRepliesRequest, opts ...grpc.CallOption) (*GetRepliesResponse, error) {
	out := new(GetRepliesResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/GetReplies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) LikeComment(ctx context.Context, in *LikeCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/LikeComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) DislikeComment(ctx context.Context, in *DislikeCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/DislikeComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) ReportComment(ctx context.Context, in *RepostCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/ReportComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) PinPost(ctx context.Context, in *PinPostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/PinPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) UnpinPost(ctx context.Context, in *UnpinPostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/UnpinPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postAPIClient) GetPins(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPinsResponse, error) {
	out := new(GetPinsResponse)
	err := c.cc.Invoke(ctx, "/KhanAPI.PostAPI/GetPins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostAPIServer is the server API for PostAPI service.
// All implementations must embed UnimplementedPostAPIServer
// for forward compatibility
type PostAPIServer interface {
	GetProfilePosts(context.Context, *GetProfilePostsRequests) (*GetProfilePostsResponse, error)
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
	SetPost(context.Context, *SetPostRequest) (*SetPostResponse, error)
	GetCategories(context.Context, *emptypb.Empty) (*GetCategoriesResponse, error)
	SuggestIngredient(context.Context, *SuggestIngredientRequest) (*SuggestIngredientResponse, error)
	AddImageForPost(context.Context, *AddImageForPostRequest) (*emptypb.Empty, error)
	Like(context.Context, *LikeRequest) (*emptypb.Empty, error)
	Dislike(context.Context, *DislikeRequest) (*emptypb.Empty, error)
	AddComment(context.Context, *AddCommentRequest) (*Comment, error)
	AddReply(context.Context, *AddReplyRequest) (*Comment, error)
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error)
	GetReplies(context.Context, *GetRepliesRequest) (*GetRepliesResponse, error)
	LikeComment(context.Context, *LikeCommentRequest) (*emptypb.Empty, error)
	DislikeComment(context.Context, *DislikeCommentRequest) (*emptypb.Empty, error)
	ReportComment(context.Context, *RepostCommentRequest) (*emptypb.Empty, error)
	PinPost(context.Context, *PinPostRequest) (*emptypb.Empty, error)
	UnpinPost(context.Context, *UnpinPostRequest) (*emptypb.Empty, error)
	GetPins(context.Context, *emptypb.Empty) (*GetPinsResponse, error)
	mustEmbedUnimplementedPostAPIServer()
}

// UnimplementedPostAPIServer must be embedded to have forward compatible implementations.
type UnimplementedPostAPIServer struct {
}

func (UnimplementedPostAPIServer) GetProfilePosts(context.Context, *GetProfilePostsRequests) (*GetProfilePostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfilePosts not implemented")
}
func (UnimplementedPostAPIServer) GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (UnimplementedPostAPIServer) SetPost(context.Context, *SetPostRequest) (*SetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPost not implemented")
}
func (UnimplementedPostAPIServer) GetCategories(context.Context, *emptypb.Empty) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedPostAPIServer) SuggestIngredient(context.Context, *SuggestIngredientRequest) (*SuggestIngredientResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestIngredient not implemented")
}
func (UnimplementedPostAPIServer) AddImageForPost(context.Context, *AddImageForPostRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddImageForPost not implemented")
}
func (UnimplementedPostAPIServer) Like(context.Context, *LikeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedPostAPIServer) Dislike(context.Context, *DislikeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Dislike not implemented")
}
func (UnimplementedPostAPIServer) AddComment(context.Context, *AddCommentRequest) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddComment not implemented")
}
func (UnimplementedPostAPIServer) AddReply(context.Context, *AddReplyRequest) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReply not implemented")
}
func (UnimplementedPostAPIServer) GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComments not implemented")
}
func (UnimplementedPostAPIServer) GetReplies(context.Context, *GetRepliesRequest) (*GetRepliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplies not implemented")
}
func (UnimplementedPostAPIServer) LikeComment(context.Context, *LikeCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeComment not implemented")
}
func (UnimplementedPostAPIServer) DislikeComment(context.Context, *DislikeCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DislikeComment not implemented")
}
func (UnimplementedPostAPIServer) ReportComment(context.Context, *RepostCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportComment not implemented")
}
func (UnimplementedPostAPIServer) PinPost(context.Context, *PinPostRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PinPost not implemented")
}
func (UnimplementedPostAPIServer) UnpinPost(context.Context, *UnpinPostRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnpinPost not implemented")
}
func (UnimplementedPostAPIServer) GetPins(context.Context, *emptypb.Empty) (*GetPinsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPins not implemented")
}
func (UnimplementedPostAPIServer) mustEmbedUnimplementedPostAPIServer() {}

// UnsafePostAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostAPIServer will
// result in compilation errors.
type UnsafePostAPIServer interface {
	mustEmbedUnimplementedPostAPIServer()
}

func RegisterPostAPIServer(s grpc.ServiceRegistrar, srv PostAPIServer) {
	s.RegisterService(&PostAPI_ServiceDesc, srv)
}

func _PostAPI_GetProfilePosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfilePostsRequests)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).GetProfilePosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/GetProfilePosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).GetProfilePosts(ctx, req.(*GetProfilePostsRequests))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_SetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).SetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/SetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).SetPost(ctx, req.(*SetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/GetCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).GetCategories(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_SuggestIngredient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestIngredientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).SuggestIngredient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/SuggestIngredient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).SuggestIngredient(ctx, req.(*SuggestIngredientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_AddImageForPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddImageForPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).AddImageForPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/AddImageForPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).AddImageForPost(ctx, req.(*AddImageForPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/Like",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).Like(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_Dislike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DislikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).Dislike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/Dislike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).Dislike(ctx, req.(*DislikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_AddComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).AddComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/AddComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).AddComment(ctx, req.(*AddCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_AddReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).AddReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/AddReply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).AddReply(ctx, req.(*AddReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_GetComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).GetComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/GetComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).GetComments(ctx, req.(*GetCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_GetReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).GetReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/GetReplies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).GetReplies(ctx, req.(*GetRepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_LikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).LikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/LikeComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).LikeComment(ctx, req.(*LikeCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_DislikeComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DislikeCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).DislikeComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/DislikeComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).DislikeComment(ctx, req.(*DislikeCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_ReportComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepostCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).ReportComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/ReportComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).ReportComment(ctx, req.(*RepostCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_PinPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PinPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).PinPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/PinPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).PinPost(ctx, req.(*PinPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_UnpinPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpinPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).UnpinPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/UnpinPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).UnpinPost(ctx, req.(*UnpinPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostAPI_GetPins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostAPIServer).GetPins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/KhanAPI.PostAPI/GetPins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostAPIServer).GetPins(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PostAPI_ServiceDesc is the grpc.ServiceDesc for PostAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KhanAPI.PostAPI",
	HandlerType: (*PostAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfilePosts",
			Handler:    _PostAPI_GetProfilePosts_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostAPI_GetPost_Handler,
		},
		{
			MethodName: "SetPost",
			Handler:    _PostAPI_SetPost_Handler,
		},
		{
			MethodName: "GetCategories",
			Handler:    _PostAPI_GetCategories_Handler,
		},
		{
			MethodName: "SuggestIngredient",
			Handler:    _PostAPI_SuggestIngredient_Handler,
		},
		{
			MethodName: "AddImageForPost",
			Handler:    _PostAPI_AddImageForPost_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _PostAPI_Like_Handler,
		},
		{
			MethodName: "Dislike",
			Handler:    _PostAPI_Dislike_Handler,
		},
		{
			MethodName: "AddComment",
			Handler:    _PostAPI_AddComment_Handler,
		},
		{
			MethodName: "AddReply",
			Handler:    _PostAPI_AddReply_Handler,
		},
		{
			MethodName: "GetComments",
			Handler:    _PostAPI_GetComments_Handler,
		},
		{
			MethodName: "GetReplies",
			Handler:    _PostAPI_GetReplies_Handler,
		},
		{
			MethodName: "LikeComment",
			Handler:    _PostAPI_LikeComment_Handler,
		},
		{
			MethodName: "DislikeComment",
			Handler:    _PostAPI_DislikeComment_Handler,
		},
		{
			MethodName: "ReportComment",
			Handler:    _PostAPI_ReportComment_Handler,
		},
		{
			MethodName: "PinPost",
			Handler:    _PostAPI_PinPost_Handler,
		},
		{
			MethodName: "UnpinPost",
			Handler:    _PostAPI_UnpinPost_Handler,
		},
		{
			MethodName: "GetPins",
			Handler:    _PostAPI_GetPins_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/post.proto",
}
